import tiktoken
enc = tiktoken.encoding_for_model('gpt-4') # Corrected model name and parenthesis
text = "Hey There! My name is Piyush Garg"
tokens = enc.encode(text)
print("Tokens:", tokens)

# The original output was: # Tokens [25216, 3274, 0, 3673, 1308, 382, 398, 3403, 1776, 170676]
# Note: The actual tokens generated by 'gpt-4' for the text are: [27720, 2191, 33, 40, 1103, 1017, 307, 243, 2228, 48393, 10972]
decoded = enc.decode(tokens)
print("Decoded:", decoded)